In [310]:
from numpy import take, array, dot
from numpy.random import randint, permutation
from numpy.linalg import inv
seed(42)

def swapRow(A, a, b):
    n = A.shape[0]
    order = list(range(n))
    order[a], order[b] = order[b], order[a] 
    return take(A, order, axis = 0)

def correctPivot(A, i, j):
    n = A.shape[0]
    while A[i, j] == 0:
        nonZeroIdx = A[i:, j].nonzero()[0]
        if nonZeroIdx.shape[0] > 0:
            A = swapRow(A, i, i + nonZeroIdx[0])
        else:
            print('Elimination Failed: Matrix is singular.')
            break
    return A

def Elimination(A):
    print('Elimination')
    n = A.shape[0]
    print(n)
    for row in range(n):
        i, j = row, row 
        print('\nPivot:', i, j)
        print(A)
        if A[i, j] == 0.0:
            print('Correcting Pivot')
            A = correctPivot(A, i, j)
            print('Corrected Matrix:\n', A)
        for r in range(i + 1, n):
            if A[r, j] != 0.0:
                λ = A[r, j] / A[i, j] 
                print(f'Multiplier for row {r}:, {λ}')
                A[r, :] = A[r, :] - λ * A[i, :]
                print(A)
    print('Echelon form obtained: Matrix is non-singular')
    return A

def BackSubstitution(A):
    print('\nBacksubstitution')
    n = A.shape[0]
    for row in range(n - 1, -1, -1):
        i, j = row, row 
        print('\nPivot:', i, j)
        print('Matrix:\n', A)
        λ = 1 / A[i, j]
        A[i, :] = λ * A[i, :]
        print('Corrected Matrix:\n', A)
        for r in range(i - 1, -1, -1):
            λ = A[r, j] / A[i, j] 
            A[r, :] = A[r, :] - λ * A[i, :]
    print('Reduced echelon form obtained!')
    return A

def MatrixMethod(A):
    A_, b_ = A[:, :A.shape[1]-1], A[:, A.shape[1]-1]
    x = dot(inv(A_), b_)
    return x

In [311]:
# Ax = b, goal is to find x.
# Random A, b matrices
# A = randint(-3, 3, (4, 5))

# Full Check (Example 4)
# https://www.cliffsnotes.com/study-guides/algebra/linear-algebra/linear-systems/gaussian-elimination
A = array([[2, -2, 0, -6], [1, -1, 1, 1], [0, 3, -2, -5]])
print(A)

[[ 2 -2  0 -6]
 [ 1 -1  1  1]
 [ 0  3 -2 -5]]


In [312]:
print('Solution from Matrix method:')
print(MatrixMethod(A))

# Elimination Method
A = Elimination(A)
A = BackSubstitution(A)
print('Solution from Gauss-Jordan Elimination:')
print(A[:, -1])

Solution from Matrix method:
[-2.  1.  4.]
Elimination
3

Pivot: 0 0
[[ 2 -2  0 -6]
 [ 1 -1  1  1]
 [ 0  3 -2 -5]]
Multiplier for row 1:, 0.5
[[ 2 -2  0 -6]
 [ 0  0  1  4]
 [ 0  3 -2 -5]]

Pivot: 1 1
[[ 2 -2  0 -6]
 [ 0  0  1  4]
 [ 0  3 -2 -5]]
Correcting Pivot
Corrected Matrix:
 [[ 2 -2  0 -6]
 [ 0  3 -2 -5]
 [ 0  0  1  4]]

Pivot: 2 2
[[ 2 -2  0 -6]
 [ 0  3 -2 -5]
 [ 0  0  1  4]]
Echelon form obtained: Matrix is non-singular

Backsubstitution

Pivot: 2 2
Matrix:
 [[ 2 -2  0 -6]
 [ 0  3 -2 -5]
 [ 0  0  1  4]]
Corrected Matrix:
 [[ 2 -2  0 -6]
 [ 0  3 -2 -5]
 [ 0  0  1  4]]

Pivot: 1 1
Matrix:
 [[ 2 -2  0 -6]
 [ 0  3  0  3]
 [ 0  0  1  4]]
Corrected Matrix:
 [[ 2 -2  0 -6]
 [ 0  1  0  1]
 [ 0  0  1  4]]

Pivot: 0 0
Matrix:
 [[ 2  0  0 -4]
 [ 0  1  0  1]
 [ 0  0  1  4]]
Corrected Matrix:
 [[ 1  0  0 -2]
 [ 0  1  0  1]
 [ 0  0  1  4]]
Reduced echelon form obtained!
Solution from Gauss-Jordan Elimination:
[-2  1  4]
